#define LAYER_STATE_8BIT
// #define PEMISSIVE_HOLD
#define TAPPING_TERM 200
#define QUICK_TAP_TERM 0
#define ACHORDION_STREAK
#define BOTH_SHIFTS_TURNS_ON_CAPS_WORD
// #define DOUBLE_TAP_SHIFT_TURNS_ON_CAPS_WORD
#define NO_ACTION_ONESHOT
#define SELECT_WORD_TIMEOUT 2000
#define NO_MUSIC_MODE
#undef LOCKING_SUPPORT_ENABLE
#undef LOCKING_RESYNC_ENABLE
